name: lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: linter
      #   uses: hexlet/project-action@release
      # - run: make lint
      # - uses: actions/checkout@v2
      # - name: linter
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - run: make lint
      - name: linter
        run: |
          make lint