name: lint

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: macos-11

    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps:

      - name: Run linter
        run: make lint